[package]
name = "user_coin"
version = "0.0.1"
edition = "2024.beta"

[dependencies]

eggx_test = { git = "https://github.com/E99-X/eggx_protocol.git", subdir = "eggx_test", rev = "registry" }
autopilot = { git = "https://github.com/E99-X/eggx_protocol.git", subdir = "autopilot", rev = "registry" }


[addresses]
user_coin = "0x0"
autopilot = "0xdcb76574b0e521b3b708c4cedc509c9050cd72f67c9bce2b782b9b382619a960"
eggx_test = "0x9543dbf51ccaed19e157ab402f9761aa5264018cda26a22c1e30c61208872c10"

